import {
  Loader2,
  Plus,
  // Health & Fitness
  Dumbbell,
  Heart,
  Activity,
  Footprints,
  Bike,
  Apple,
  Moon,
  // Food & Drink
  Coffee,
  Utensils,
  GlassWater,
  Beer,
  Pizza,
  Carrot,
  // Productivity
  Zap,
  Target,
  CheckCircle,
  Clock,
  Calendar,
  BookOpen,
  Crosshair,
  // Tech & Work
  Laptop,
  Code,
  Briefcase,
  Wifi,
  Monitor,
  Keyboard,
  Smartphone,
  Server,
  // Finance
  DollarSign,
  CreditCard,
  PiggyBank,
  Wallet,
  TrendingUp,
  BarChart,
  // Creativity
  Palette,
  Music,
  Camera,
  PenTool,
  Lightbulb,
  Image,
  // Social & Family
  Users,
  MessageCircle,
  Phone,
  Home,
  Gift,
  // Nature & Travel
  Sun,
  Cloud,
  Plane,
  Map as MapIcon,
  Mountain,
  Trees,
  Umbrella,
  // Home & Lifestyle
  Bed,
  Bath,
  Sofa,
  ShoppingCart,
  Tag,
  // Other
  Star,
  Flag,
  Smile,
  Ghost,
  Skull,
  Trophy,
  LucideIcon,
} from 'lucide-react';

// Helper to flatten icons for easy lookup
export const ALL_ICONS: Record<string, LucideIcon> = {
  // Health
  dumbbell: Dumbbell,
  heart: Heart,
  activity: Activity,
  footprints: Footprints,
  bike: Bike,
  apple: Apple,
  moon: Moon,
  // Food
  coffee: Coffee,
  utensils: Utensils,
  glasswater: GlassWater,
  beer: Beer,
  pizza: Pizza,
  carrot: Carrot,
  // Productivity
  zap: Zap,
  target: Target,
  checkcircle: CheckCircle,
  clock: Clock,
  calendar: Calendar,
  bookopen: BookOpen,
  crosshair: Crosshair,
  // Tech
  laptop: Laptop,
  code: Code,
  briefcase: Briefcase,
  wifi: Wifi,
  monitor: Monitor,
  keyboard: Keyboard,
  smartphone: Smartphone,
  server: Server,
  // Finance
  dollarsign: DollarSign,
  creditcard: CreditCard,
  piggybank: PiggyBank,
  wallet: Wallet,
  trendingup: TrendingUp,
  barchart: BarChart,
  // Creativity
  palette: Palette,
  music: Music,
  camera: Camera,
  pentool: PenTool,
  lightbulb: Lightbulb,
  image: Image,
  // Social
  users: Users,
  messagecircle: MessageCircle,
  phone: Phone,
  home: Home,
  gift: Gift,
  // Nature
  sun: Sun,
  cloud: Cloud,
  plane: Plane,
  map: MapIcon,
  mountain: Mountain,
  trees: Trees,
  umbrella: Umbrella,
  // Home
  bed: Bed,
  bath: Bath,
  sofa: Sofa,
  shoppingcart: ShoppingCart,
  tag: Tag,
  // Other
  star: Star,
  flag: Flag,
  smile: Smile,
  ghost: Ghost,
  skull: Skull,
  trophy: Trophy,
};

export const ICON_CATEGORIES = [
  {
    name: 'Health & Fitness',
    icons: [
      'dumbbell',
      'heart',
      'activity',
      'footprints',
      'bike',
      'apple',
      'moon',
    ],
  },
  {
    name: 'Food & Drink',
    icons: ['coffee', 'utensils', 'glasswater', 'beer', 'pizza', 'carrot'],
  },
  {
    name: 'Productivity',
    icons: [
      'zap',
      'target',
      'checkcircle',
      'clock',
      'calendar',
      'bookopen',
      'crosshair',
    ],
  },
  {
    name: 'Tech & Work',
    icons: [
      'laptop',
      'code',
      'briefcase',
      'wifi',
      'monitor',
      'keyboard',
      'smartphone',
      'server',
    ],
  },
  {
    name: 'Finance',
    icons: [
      'dollarsign',
      'creditcard',
      'piggybank',
      'wallet',
      'trendingup',
      'barchart',
    ],
  },
  {
    name: 'Creativity',
    icons: ['palette', 'music', 'camera', 'pentool', 'lightbulb', 'image'],
  },
  {
    name: 'Social & Family',
    icons: ['users', 'heart', 'messagecircle', 'phone', 'home', 'gift'],
  },
  {
    name: 'Nature & Travel',
    icons: ['sun', 'cloud', 'plane', 'map', 'mountain', 'trees', 'umbrella'],
  },
  {
    name: 'Home & Lifestyle',
    icons: ['home', 'bed', 'bath', 'sofa', 'shoppingcart', 'tag'],
  },
  {
    name: 'Other',
    icons: ['star', 'flag', 'smile', 'ghost', 'skull', 'trophy'],
  },
];
